apiVersion: backstage.io/v1beta2
kind: Template
metadata:
  name: ansible-python-install
  title: Ansible Python Install Template
  description: Generate Ansible playbook to install Python on remote machines
spec:
  type: code
  path: ansible-python-install
  schema:
    properties:
      machine_count:
        type: integer
        title: Machine Count
        description: Number of remote machines to install Python on
        default: 2
    required:
      - machine_count
  steps:
    - id: generate-playbook
      name: Generate Ansible Playbook
      action: template:generate
      input:
        templatePath: ./ansible-python-install/playbook.yml
        outputPath: ${{ entityPath }}/playbook.yml
        values:
          machine_count: ${{ parameters.machine_count }}
